name: stock_cmd
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6

  shared_preferences: ^2.3.3

  cupertino_icons: ^1.0.8

  # 屏幕适配  https://github.com/OpenFlutter/flutter_screenutil
  flutter_screenutil: ^5.9.3

  #  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4

  logger: ^2.5.0

  window_manager: ^0.4.3

  image_picker: ^1.1.2
  clipboard: ^0.1.3
  image: ^4.4.0
  path_provider: ^2.1.5
  path: ^1.9.0

  http: ^1.2.2
  html: ^0.15.5
  dio: ^5.7.0
  flutter_smart_dialog: ^4.9.8+5


  gbk_codec: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
